# NumPy

In [1]:
import numpy as np

In [2]:
# Create a 4X2 integer array and Prints its attributes
firstarray= np.empty([4,2],dtype=np.uint16)
print(firstarray)

print("1> Array Shape is:",firstarray.shape)
print("2>. Array dimensions are",firstarray.ndim)
print("3>. Length of each element of array in bytes is", firstarray.itemsize)

[[51974 31337]
 [ 9658  5186]
 [24173 10289]
 [37783 62265]]
1> Array Shape is: (4, 2)
2>. Array dimensions are 2
3>. Length of each element of array in bytes is 2


In [26]:
# Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10 

Array1=np.arange(100,200,10)
Array1=Array1.reshape(5,2)
print(Array1)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [28]:
# Following is the provided numPy array. return array of items in the third column from all rows
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

sampleArray

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [5]:
sampleArray[:,2]

array([33, 66, 99])

In [6]:
# Following is the given numpy array return array of odd rows and even columns

sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
sampleArray

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [7]:
print(sampleArray[0::2,1::2])

[[ 6 12]
 [30 36]
 [54 60]]


In [30]:
# Add the following two NumPy arrays and Modify a result array by calculating the square of each element
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

array=arrayOne+arrayTwo

for i in array:
    print(i*i)
    i=i+1

[ 400 1521 1089]
[625 625 784]


In [9]:
# Split the array into four equal-sized sub-arrays
array=np.arange(10,34,1)

array1=array.reshape(8,3)
array1

subarray=np.split(array1,4)
subarray

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [10]:
# Sort following NumPy array
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [35]:
sampleArray1=sampleArray[:,sampleArray[1,:].argsort()]

In [36]:
print(sampleArray1)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [33]:
sampleArray2=sampleArray[sampleArray[:,1].argsort()]

In [34]:
print(sampleArray2)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [42]:
#  Following is the 2-D array. Print max from axis 0 and min from axis 1
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray
sampleArray1=np.amax(sampleArray,0)
sampleArray2=np.amin(sampleArray,1)

In [16]:
sampleArray


array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [17]:
sampleArray1

array([82, 94, 73])

In [43]:
sampleArray2

array([34, 12, 53])

In [19]:
# Following is the input NumPy array delete column two and insert following new column in its place.

sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 

newColumn = np.array([[10,10,10]])

In [20]:
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [45]:
sampleArray1=np.insert(sampleArray,1,newColumn,axis=1)
sampleArray2=np.delete(sampleArray1,2,axis=1)

In [22]:
sampleArray1

array([[34, 10, 43, 73],
       [82, 10, 22, 12],
       [53, 10, 94, 66]])

In [23]:
sampleArray2

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [24]:
# Create a two 2-D array and Plot it using matplotlib